### ISSUE TITLE
[Bug]: Icons Disappear on Reboot (Silverblue)

### ISSUE THREAD

**Issue by tfranken90** [fabrialberio/PinApp#22]
### Describe the bug
I'm running Fedora Silverblue. When I reboot my system, icons stored in /run/user/1000/doc/ disappear. 

What did you expect to happen?
I expected the icons to persist across boots. It would be nice if the icons could be stored in a hidden home directory like .local 

 ### To Reproduce
1. Set Icons
2. Reboot

### Linux distribution
In which Linux distribution did you encounter the bug? Fedora Silverblue
Which desktop environment were you using? GNOME

**Comment by tfranken90** [comment]
This appears to have stopped happening. I'm not sure what the issue was. I will close and reopen if I notice it happening again.

**Comment by not-a-dev-stein** [comment]
It still happens in my case, and I think it has something to do with the file chooser portal.

If you set the icon's path manually (eg.: `/var/home/$USER/.local/share/icons/icon-name.png`) everything works consistently, but if you use the file picker in the app the resulting path shown will be something similar to `/run/user/1000/doc/58377364/icon-name.png`, which results in the icon showing normally until the next reboot.

I'm not well versed with Flatpak devel stuff, nor with portal stuff, but I do believe that's where the issue comes from.

**Comment by tfranken90** [comment]
It's happening again for me as well, but it's intermittent. Sometimes the icons are there and sometimes they are not.

**Comment by fabrialberio** [comment]
I have tried to replicate this issue, but I am having trouble emulating Fedora Silverblue, and I don't have a device to install it on.
I'll add a "could not replicate" label for now.

**Comment by thatLeaflet** [comment]
> It still happens in my case, and I think it has something to do with the file chooser portal.
> 
> If you set the icon's path manually (eg.: `/var/home/$USER/.local/share/icons/icon-name.png`) everything works consistently, but if you use the file picker in the app the resulting path shown will be something similar to `/run/user/1000/doc/58377364/icon-name.png`, which results in the icon showing normally until the next reboot.
> 
> I'm not well versed with Flatpak devel stuff, nor with portal stuff, but I do believe that's where the issue comes from.

If this is the case, then I think the issue is rather easy to fix. That /run/user/... directory is indicative of how portals handle exposing files to sandboxed apps. It basically makes a file that isn't available from the default sandbox available temporarily, seemingly until the next reboot. So rather than using the the exact picture the user selects (example: ~/Pictures/appPicture.png), PinApp should instead make a copy of that icon and store it in a sandbox accessible location (example: ~/.var/app/io.github.fabrialberio.pinapp/data/icons).

**Comment by tfranken90** [comment]
For now, I just place my icons in ~/.local/share/icons which allows me to just reference the files by name. However, while this works for the application launcher, PinApp doesn't display the icon.

**Comment by fabrialberio** [comment]
Implemented @thatLeaflet 's suggestion, now the icon is copied inside the app data directory and should persist after reboot.
