### ISSUE TITLE
Change app icon by clicking on it

### ISSUE THREAD

**Issue by octowaddle** [fabrialberio/PinApp#3]
You should be able to change an app icon by clicking on it and selecting an image file.

**Comment by fabrialberio** [comment]
I agree that there needs to be an easy way to upload a file as an icon, and clicking on the icon would be quite an intuitive way.

The simplest way to do so would be something like the file properties pane in Nautilus, where clicking on the icon displays a file chooser, although this raises some issues:
- In my opinion this would make the "Icon" entry row quite ambiguous
- How are you supposed to discover that the icon is a button? Making it a raised button like in Nautilus would look out of place in the app.

I think a better solution would be adding a suffix icon to the "Icon" row that opens a file chooser. It should also be possible to make it so clicking on the icon focuses "icon" row, so that the connections between the two elements is clear, but it seems a bit too complicated

**Comment by fabrialberio** [comment]
I've added a button to upload an image as a suffix in the Icon entry row, that should do the job
